//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsForEverApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medewerkers
    {
        public int Medewerkerscode { get; set; }
        public string Voorletters { get; set; }
        public string Voorvoegsels { get; set; }
        public string Achternaam { get; set; }
        public string Gebruikersnaam { get; set; }
        public bool Type { get; set; }
        public string Email { get; set; }
        public string AspNetUserID { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
