//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsForEverApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voorraad
    {
        public int Locatiecode { get; set; }
        public int Productcode { get; set; }
        public int Aantal { get; set; }
    
        public virtual Artikel Artikel { get; set; }
        public virtual Locatie Locatie { get; set; }
    }
}
